iotaledger/documentation-platform

src/contentHomePage.json
Update a few links and change a title
=> Patch: Update homepage links

buildSearchIndex.js, package-lock.json, package.json, src/containers/Search.js, yarn.lock
Use Fuse.Js over Lunr due to fuzzy and ranked searches
=> Change search method

src/components/atoms/GoogleAnalytics/index.js, src/components/atoms/HotJar/index.js, src/components/molecules/TableOfContents/index.js, src/containers/Doc.js, src/utils/scroll.js
Updated url window url with the anchor tag when clicking on toc link.
=> Fix toc url anchor

buildProjects.config.json, buildProjects.js, buildSearchIndex.js
Search indexer broken when file was missing, improved error handling.
=> Improve error handling

src/components/organisms/Header/index.js, src/components/organisms/StickyHeader/index.js, src/containers/Doc.js, src/containers/Home.js, src/containers/NotFound.js, src/containers/Search.js, src/utils/propTypes.js
Add option in view settings that allows search to be disabled.
Also make popular topics in content.json not required.
These features are both for use by the training site.
=> Feature to disable search

.dockerignore, buildProjects.js
Check case sensitivity of folders
Allow config files in docker content
=> Check case sensitivity of folders

src/components/organisms/Markdown/markdown.css
Fixes image popup not showing on Firefox
=> Update image popup css to work on firefox

buildProjects.js
Skip validation of mailto links, required for training portal.
=> Add mailto link checks

Dockerfile
Remove single page flag from serve command which breaks navigation for react static apps
=> Remove single page flag from serve command

src/containers/Home.js, static.config.js
If the site builder finds a home.html in the site-settings folder for the content it will use that instead of the standard home page.
=> Added feature to load static home page

now.json, static.config.js
Allows assets referenced in static home page to be mapped into final production build.
=> Static home remap assets

package-lock.json, package.json
=> Updated axios to 0.19.0

src/components/atoms/MarkdownCard/index.js, src/components/organisms/Markdown/index.js, src/components/organisms/Markdown/markdown.css
Implementation of cards for markdown see https://github.com/iotaledger/documentation/blob/feature/cards/docs/MARKDOWN.md#cards for usage
=> Added cards

src/components/organisms/Markdown/index.js
Fixed links to local files in project topic headers.
=> Fix project topic links for local files

src/components/molecules/SideMenu/index.js, src/components/molecules/TreeMenu/index.js, src/components/organisms/Markdown/index.js
Add indicator adornments to sub-level navigation
=> Added sub navigation styling

Dockerfile, api/Dockerfile
Zeit now changed the config parser so only single port expose is supported
=> Fix dockerfile expose

package-lock.json, package.json, src/components/atoms/Disclaimer/disclaimer.css, src/components/atoms/Disclaimer/index.js, src/containers/Container.js
Disclaimer added for cookie usage.
=> Added disclaimer

package-lock.json, package.json, src/components/organisms/Markdown/index.js, src/components/organisms/Markdown/markdown.css
Fixed indentation in tabbed content when it is not code.
Also updated the syntax highlighter to include more languages.
=> Fixed indentation in tab control

src/utils/projects.js
Fix error when there is an empty index
=> Fix the error on empty index

src/containers/Doc.js
Fixes https://github.com/iotaledger/documentation-platform/issues/273
=> Fix version selector reload
